=== BernhardWebstudio/PreCapture/supporting/LabelDefinitionSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mcz.harvard.edu/LabelDefinitionSchema" xmlns:tns="http://mcz.harvard.edu/LabelDefinitionSchema" elementFormDefault="qualified">

    <element name="LabelDefinitions"
    	type="tns:LabelDefinitionListType">
    </element>

    <complexType name="LabelDefinitionType">
    	<sequence>
    		<element name="Title" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="Units" type="tns:UnitsType" maxOccurs="1" minOccurs="1"></element>
    		<element name="PaperHeight" type="float" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="PaperWidth" type="float" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="Margins" type="float" maxOccurs="1" minOccurs="1"></element>
    		<element name="Columns" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="LabelWidth" type="float" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="LabelHeight" type="float" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="TextOrentation" type="tns:TextOrentationType"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>


    <simpleType name="TextOrentationType">
    	<restriction base="string">
    		<enumeration value="Horizontal"></enumeration>
    		<enumeration value="Vertical"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="UnitsType">
    	<restriction base="string">
    		<enumeration value="Inches"></enumeration>
    		<enumeration value="cm"></enumeration>
    	</restriction>
    </simpleType>



    <complexType name="LabelDefinitionListType">
    	<sequence>
    		<element name="LabelDefinition" type="tns:LabelDefinitionType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== BernhardWebstudio/PreCapture/src/edu/harvard/mcz/precapture/resources/LabelDefinitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:LabelDefinitions xmlns:tns="http://mcz.harvard.edu/LabelDefinitionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mcz.harvard.edu/LabelDefinitionSchema ../../../../../../supporting/LabelDefinitionSchema.xsd ">
  <tns:LabelDefinition>
    <tns:Title>Full Sheet</tns:Title>
    <tns:Units>Inches</tns:Units>
    <tns:PaperHeight>11</tns:PaperHeight>
    <tns:PaperWidth>8.5</tns:PaperWidth>
    <tns:Margins>.5</tns:Margins>
    <tns:Columns>1</tns:Columns>
    <tns:LabelWidth>7.5</tns:LabelWidth>
    <tns:LabelHeight>10</tns:LabelHeight>
    <tns:TextOrentation>Horizontal</tns:TextOrentation>
  </tns:LabelDefinition>
  <tns:LabelDefinition>
    <tns:Title>Half Sheet</tns:Title>
    <tns:Units>Inches</tns:Units>
    <tns:PaperHeight>11</tns:PaperHeight>
    <tns:PaperWidth>8.5</tns:PaperWidth>
    <tns:Margins>.5</tns:Margins>
    <tns:Columns>2</tns:Columns>
    <tns:LabelWidth>3.25</tns:LabelWidth>
    <tns:LabelHeight>10</tns:LabelHeight>
    <tns:TextOrentation>Vertical</tns:TextOrentation>
  </tns:LabelDefinition>
  <tns:LabelDefinition>
    <tns:Title>2.5x4 on Paper</tns:Title>
    <tns:Units>Inches</tns:Units>
    <tns:PaperHeight>11</tns:PaperHeight>
    <tns:PaperWidth>8.5</tns:PaperWidth>
    <tns:Margins>.5</tns:Margins>
    <tns:Columns>2</tns:Columns>
    <tns:LabelWidth>3.25</tns:LabelWidth>
    <tns:LabelHeight>2.5</tns:LabelHeight>
    <tns:TextOrentation>Horizontal</tns:TextOrentation>
  </tns:LabelDefinition>
  <tns:LabelDefinition>
    <tns:Title>4x2.3"Label</tns:Title>
    <tns:Units>Inches</tns:Units>
    <tns:PaperHeight>2.3125</tns:PaperHeight>
    <tns:PaperWidth>4</tns:PaperWidth>
    <tns:Margins>.1</tns:Margins>
    <tns:Columns>1</tns:Columns>
    <tns:LabelWidth>3.8</tns:LabelWidth>
    <tns:LabelHeight>2.1125</tns:LabelHeight>
    <tns:TextOrentation>Horizontal</tns:TextOrentation>
  </tns:LabelDefinition>  
</tns:LabelDefinitions>

=== BernhardWebstudio/PreCapture/bin/edu/harvard/mcz/precapture/resources/LabelDefinitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:LabelDefinitions xmlns:tns="http://mcz.harvard.edu/LabelDefinitionSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://mcz.harvard.edu/LabelDefinitionSchema LabelDefinitionSchema.xsd ">
  <tns:LabelDefinition>
    <tns:Title>Full Sheet 8.5x11</tns:Title>
    <tns:Units>Inches</tns:Units>
    <tns:PaperHeight>11</tns:PaperHeight>
    <tns:PaperWidth>8.5</tns:PaperWidth>
    <tns:Margins>.5</tns:Margins>
    <tns:Columns>1</tns:Columns>
    <tns:LabelWidth>7.5</tns:LabelWidth>
    <tns:LabelHeight>10</tns:LabelHeight>
    <tns:TextOrentation>Horizontal</tns:TextOrentation>
  </tns:LabelDefinition>
  <tns:LabelDefinition>
    <tns:Title>Two Half Sheets on 8.5x11</tns:Title>
    <tns:Units>Inches</tns:Units>
    <tns:PaperHeight>11</tns:PaperHeight>
    <tns:PaperWidth>8.5</tns:PaperWidth>
    <tns:Margins>.5</tns:Margins>
    <tns:Columns>2</tns:Columns>
    <tns:LabelWidth>3.25</tns:LabelWidth>
    <tns:LabelHeight>10</tns:LabelHeight>
    <tns:TextOrentation>Vertical</tns:TextOrentation>
  </tns:LabelDefinition>
  <tns:LabelDefinition>
    <tns:Title>Multiple 2.5x4 slips on 8.5x11</tns:Title>
    <tns:Units>Inches</tns:Units>
    <tns:PaperHeight>11</tns:PaperHeight>
    <tns:PaperWidth>8.5</tns:PaperWidth>
    <tns:Margins>.5</tns:Margins>
    <tns:Columns>2</tns:Columns>
    <tns:LabelWidth>3.25</tns:LabelWidth>
    <tns:LabelHeight>2.5</tns:LabelHeight>
    <tns:TextOrentation>Horizontal</tns:TextOrentation>
  </tns:LabelDefinition>
  <tns:LabelDefinition>
    <tns:Title>2.3x4" Dymo LabelWriter</tns:Title>
    <tns:Units>Inches</tns:Units>
    <tns:PaperHeight>3.9</tns:PaperHeight>
    <tns:PaperWidth>2.3125</tns:PaperWidth>
    <tns:Margins>.1</tns:Margins>
    <tns:Columns>1</tns:Columns>
    <tns:LabelWidth>2.1125</tns:LabelWidth>
    <tns:LabelHeight>3.7</tns:LabelHeight>
    <tns:TextOrentation>Vertical</tns:TextOrentation>
  </tns:LabelDefinition>    
  <tns:LabelDefinition>
    <tns:Title>4x2.3"Label</tns:Title>
    <tns:Units>Inches</tns:Units>
    <tns:PaperHeight>2.3125</tns:PaperHeight>
    <tns:PaperWidth>4</tns:PaperWidth>
    <tns:Margins>.1</tns:Margins>
    <tns:Columns>1</tns:Columns>
    <tns:LabelWidth>3.8</tns:LabelWidth>
    <tns:LabelHeight>2.1125</tns:LabelHeight>
    <tns:TextOrentation>Horizontal</tns:TextOrentation>
  </tns:LabelDefinition>  
</tns:LabelDefinitions>
